### ISSUE TITLE
Search fails 500 error in ibm-et/jupyter-samples binder

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/contentmanagement#9]
Can't get to the binder logs, but it looks like the problem might be with the content being indexed, not the environment. Try to copy the entire contents into a local dev env and run the search to see if it can be reproduced.

**Comment by parente** [comment]
```
    Traceback (most recent call last):
      File "/home/main/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/main/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2717, in wrapper
        return method(self, *args, **kwargs)
      File "/home/main/anaconda/lib/python2.7/site-packages/urth/cms/search.py", line 21, in get
        self.index.update_index()
      File "/home/main/anaconda/lib/python2.7/site-packages/urth/cms/index.py", line 124, in update_index
        self._add_to_index(writer, to_add, on_disk)
      File "/home/main/anaconda/lib/python2.7/site-packages/urth/cms/index.py", line 93, in _add_to_index
        writer.add_document(**meta)
      File "/home/main/anaconda/lib/python2.7/site-packages/whoosh/writing.py", line 750, in add_document
        for tbytes, freq, weight, vbytes in items:
      File "/home/main/anaconda/lib/python2.7/site-packages/whoosh/fields.py", line 156, in index
        raise ValueError("%r is not unicode or sequence" % value)
    ValueError: '' is not unicode or sequence
```

Reproduced locally. Unicode handling. Possibly python2 v 3 thing as well.

**Comment by parente** [comment]
Loaded the jupyter_samples notebooks into a local dev environment running on Python 3. Did not hit the bug. More evidence this is a python2 problem.

Next step: get the dev environment running on python2 as well as 3.

**Comment by parente** [comment]
Confirmed fixed locally. Updated jupyter-samples binder. Confirmed fixed there too.

<img width="1232" alt="screen shot 2015-11-22 at 12 25 33 am" src="https://cloud.githubusercontent.com/assets/153745/11322219/8ebffbac-90af-11e5-85d2-36b07c12c9de.png">
